### ISSUE TITLE
 dtype must be explicitly provided

### ISSUE THREAD

**Issue by Amakri1020** [carla-rl-gym/carla-rl#5]
Hi, I followed the instructions in the README but with the carla server running, when try to run a client I get the following error:

:/app# python client/train.py --config client/config/a2c.yaml 
Environment 0 running in port 2000
Trying to make client on port 2000
Environment 1 running in port 2003
Trying to make client on port 2003
Environment 2 running in port 2006
Trying to make client on port 2006
Environment 3 running in port 2009
Trying to make client on port 2009
Environment 4 running in port 2012
Trying to make client on port 2012
Environment 5 running in port 2015
Trying to make client on port 2015
Environment 6 running in port 2018
Trying to make client on port 2018
Environment 7 running in port 2021
Trying to make client on port 2021
Successfully made client on port 2000
Traceback (most recent call last):
  File "client/train.py", line 301, in <module>
    main()
  File "client/train.py", line 117, in main
    video_every=args.video_interval, video_dir=os.path.join(args.save_dir, 'video', experiment_name))
  File "/app/client/envs_manager.py", line 45, in make_vec_envs
    envs = VecPyTorchFrameStack(envs, num_frame_stack, device)
  File "/app/client/envs_manager.py", line 139, in __init__
    low=low, high=high, dtype=venv.observation_space.dtype)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/gym/spaces/box.py", line 21, in __init__
    assert dtype is not None, 'dtype must be explicitly provided. '

And from the server:
[2019.05.03-03.33.36:809][  0]LogContentStreaming: Texture pool size now 2000 MB
[2019.05.03-03.33.37:044][  1]LogLinux: Setting swap interval to 'Immediate'
[2019.05.03-03.33.37:044][  1]LogLinux: Warning: Unable to set desired swap interval 'Immediate'
ERROR:ERROR: tcpserver  tcpserver 2002 2000 : error reading message: End of file: error reading message: End of file 
 
[2019.05.03-03.33.38:873][  3]LogCarlaServer: Warning: Client disconnected, server needs restart
[2019.05.03-03.33.38:873][  3]LogCarlaServer: Restarting the level...
[2019.05.03-03.33.38:885][  4]LogNet: Browse: /Game/Maps/Town01?Name=Player?restart
[2019.05.03-03.33.38:896][  4]LogLoad: LoadMap: /Game/Maps/Town01?Name=Player
[2019.05.03-03.33.41:203][  4]LogAIModule: Creating AISystem for world Town01
[2019.05.03-03.33.41:399][  4]LogLoad: Game class is 'CarlaGameMode_C'
[2019.05.03-03.33.41:657][  4]LogWorld: Bringing World /Game/Maps/Town01.Town01 up for play (max tick rate 0) at 2019.05.03-03.33.41
[2019.05.03-03.33.41:658][  4]LogCarla: Loading weather description from ../../../CarlaUE4/Config/CarlaWeather.ini
[2019.05.03-03.33.41:659][  4]LogCarla: Loading weather description from ../../../CarlaUE4/Config/CarlaWeather.Town01.ini
[2019.05.03-03.33.41:661][  4]LogCarlaServer: Waiting for the client to connect...
^C[2019.05.03-03.33.42:370][  4]LogLinux: FLinuxPlatformMisc::RequestExit(bForce=false, ReturnCode=130)
[2019.05.03-03.33.42:370][  4]LogLinux: FLinuxPlatformMisc::RequestExit(0)
[2019.05.03-03.33.42:370][  4]LogGenericPlatformMisc: FPlatformMisc::RequestExit(0)
ERROR:[2019.05.03-03.33.51:661][  4]LogCarlaServer: Warning: Failed to initialize, server needs restart
 tcpserver 0 : connection failed: Operation canceled 

Any ideas on why this is occurring?

**Comment by matosjr** [comment]
I had the same problem.
Installing gym version 0.10.8 solved it for me.
